### ISSUE TITLE
Error during npm start command

### ISSUE THREAD

**Issue by cveksitron** [Microsoft/TypeScript-Node-Starter#108]
Hi guys,

I'm getting following error during npm start command:

`debug: Logging initialized at debug level
debug: Using .env.example file to supply config environment variables
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1019:11)
    at _exceptionWithHostPort (util.js:1041:20)
    at Server.setupListenHandle [as _listen2] (net.js:1344:14)
    at listenInCluster (net.js:1385:12)
    at Server.listen (net.js:1469:7)
    at Function.listen (/home/user/projects/test/TypeScript-Node-Starter/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/user/projects/test/TypeScript-Node-Starter/dist/server.js:15:30)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! express-typescript-starter@0.1.0 serve: `node dist/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the express-typescript-starter@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-04-05T09_41_53_909Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! express-typescript-starter@0.1.0 start: `npm run serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the express-typescript-starter@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-04-05T09_41_53_922Z-debug.log
`

Can somebody help me?

Many thanks.

**Comment by welkie** [comment]
I notice you closed the issue already. If you still need help solving it, this is a fairly common error and easy to solve. It just means that at the time you ran that command, you were already serving an application on port 3000, so it wasn't able to bind to it. You can solve it by figuring out what you had running on port 3000 and stopping it. Then, you'll be able to start this one on port 3000.
