### ISSUE TITLE
App Service: "Application Error" -  Cannot find module '../lib/utils/unsupported.js'

### ISSUE THREAD

**Issue by simkessy** [microsoft/TypeScript-Node-Starter#193]
I've tried to follow these steps but the application is now saying "Application Error" 

I looked at the logs and I see this: 

```
Debugger listening on ws://0.0.0.0:49494/703f9862-c7bf-4f73-8803-e3de51b27f78
For help see https://nodejs.org/en/docs/inspector
module.js:549
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /home/site/wwwroot/node_modules/.bin/npm:19:21
    at Object.<anonymous> (/home/site/wwwroot/node_modules/.bin/npm:152:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@1.0.0 start: `npm run serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-10T03_44_47_900Z-debug.log
```

I've deployed using Node LTS 10, 8 and 6. 

I'm using DevOps to deploy: 

![image](https://user-images.githubusercontent.com/5871660/59211841-bd930f00-8b65-11e9-95f0-e629125739eb.png)

Pipelines: Agent Pool Ubuntu 1604
Get Sources: Azure Repos
npm i npm@latest
npm i -g typescript ts-lint
npm i 
npm run build 

![image](https://user-images.githubusercontent.com/5871660/59211949-064ac800-8b66-11e9-8f50-e88c04ddbc97.png)

Package.js scripts: 

```
  "scripts": {
    "start": "npm run serve",
    "serve": "node dist/index.js",
    "prebuild": "tslint -c tslint.json -p tsconfig.json --fix 'src/**/*'",
    "build": "tsc",
    "dev": "nodemon --exec ts-node src\\index.ts",
    "d": "nodemon -r esm src\\index.ts",
    "check-types": "tsc",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```
App Service Files: 

![image](https://user-images.githubusercontent.com/5871660/59212088-53c73500-8b66-11e9-8a7e-b18dfc8b450a.png)

**Comment by peterblazejewicz** [comment]
Can you switch to the 10? (the latest version should work OK with the 10 TLS release). We are using Node 10 with Azure DevOps at work for very different task and yet it never failed.
