### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by vanhumbeecka** [Microsoft/TypeScript-Node-Starter#20]
After running ```yarn install```, i run the build.
```yarn run build``` returns the following error:

```
$ yarn run build
yarn run v0.27.5
$ npm run build-sass && npm run build-ts && npm run tslint && npm run copy-static-assets
module.js:471
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`
``

**Comment by vanhumbeecka** [comment]
Ok, solved it myself:
https://stackoverflow.com/questions/43578121/how-to-fix-broken-npm-after-node-update
