### ISSUE TITLE
mongo setup not working

### ISSUE THREAD

**Issue by JohnReedLOL** [microsoft/TypeScript-Node-Starter#40]
I am new to this stack and would like my starter to work "out of the box".

I installed mongodb like so:

https://www.howtoforge.com/tutorial/install-mongodb-on-ubuntu-16.04/

When I try to run it I get:

```
$ npm start

> express-typescript-starter@0.1.0 start /home/ubuntu/projects/project2
> npm run build && npm run watch


> express-typescript-starter@0.1.0 build /home/ubuntu/projects/project2
> npm run build-sass && npm run build-ts && npm run tslint && npm run copy-static-assets


> express-typescript-starter@0.1.0 build-sass /home/ubuntu/projects/project2
> node-sass src/public/css/main.scss dist/public/css/main.css

Rendering Complete, saving .css file...
Wrote CSS to /home/ubuntu/projects/project2/dist/public/css/main.css

> express-typescript-starter@0.1.0 build-ts /home/ubuntu/projects/project2
> tsc


> express-typescript-starter@0.1.0 tslint /home/ubuntu/projects/project2
> tslint -c tslint.json -p tsconfig.json




> express-typescript-starter@0.1.0 copy-static-assets /home/ubuntu/projects/project2
> node copyStaticAssets.js


> express-typescript-starter@0.1.0 watch /home/ubuntu/projects/project2
> concurrently -k -p "[{name}]" -n "Sass,TypeScript,Node" -c "yellow.bold,cyan.bold,green.bold" "npm run watch-sass" "npm run watch-ts" "npm run serve"

[Node] 
[Node] > express-typescript-starter@0.1.0 serve /home/ubuntu/projects/project2
[Node] > nodemon dist/server.js
[Node] 
[TypeScript] 
[TypeScript] > express-typescript-starter@0.1.0 watch-ts /home/ubuntu/projects/project2
[TypeScript] > tsc -w
[TypeScript] 
[Sass] 
[Sass] > express-typescript-starter@0.1.0 watch-sass /home/ubuntu/projects/project2
[Sass] > node-sass -w src/public/css/main.scss dist/public/css/main.css
[Sass] 
[Node] [nodemon] 1.11.0
[Node] [nodemon] to restart at any time, enter `rs`
[Node] [nodemon] watching: *.*
[Node] [nodemon] starting `node dist/server.js`
[Node] Unhandled rejection MongoError: not authorized on admin to execute command { listIndexes: "sessions", cursor: {} }
[Node]     at Function.MongoError.create (/home/ubuntu/projects/project2/node_modules/mongodb-core/lib/error.js:31:11)
[Node]     at queryCallback (/home/ubuntu/projects/project2/node_modules/mongodb-core/lib/cursor.js:212:36)
[Node]     at /home/ubuntu/projects/project2/node_modules/mongodb-core/lib/connection/pool.js:469:18
[Node]     at _combinedTickCallback (internal/process/next_tick.js:131:7)
[Node]     at process._tickCallback (internal/process/next_tick.js:180:9)
[Node] [nodemon] restarting due to changes...
[Node] [nodemon] starting `node dist/server.js`
[Node] [nodemon] restarting due to changes...
[Node] [nodemon] starting `node dist/server.js`
[Node] [nodemon] restarting due to changes...
[Node] [nodemon] restarting due to changes...
[Node] [nodemon] restarting due to changes...
[Node] [nodemon] starting `node dist/server.js`
[Node] [nodemon] restarting due to changes...
[Node] [nodemon] restarting due to changes...
[TypeScript] 21:13:36 - Compilation complete. Watching for file changes.
[TypeScript] 
[TypeScript] 
[Node] [nodemon] restarting due to changes...
[Node] [nodemon] starting `node dist/server.js`
[Node] Unhandled rejection MongoError: not authorized on admin to execute command { listIndexes: "sessions", cursor: {} }
[Node]     at Function.MongoError.create (/home/ubuntu/projects/project2/node_modules/mongodb-core/lib/error.js:31:11)
[Node]     at queryCallback (/home/ubuntu/projects/project2/node_modules/mongodb-core/lib/cursor.js:212:36)
[Node]     at /home/ubuntu/projects/project2/node_modules/mongodb-core/lib/connection/pool.js:469:18
[Node]     at _combinedTickCallback (internal/process/next_tick.js:131:7)
[Node]     at process._tickCallback (internal/process/next_tick.js:180:9)
```

As you can see Mongo is giving me an error.

**Comment by JohnReedLOL** [comment]
Also, if you could let me know how to access the app from my laptop's browser that would be great.

**Comment by kevinxh** [comment]
Cloned this repo today and MongoDB works fine for me.

MongoDB version: `v3.4.9`

**Comment by orta** [comment]
I agree 👍
